### ISSUE TITLE
Account where a certain field (int) is empty

### ISSUE THREAD

**Issue by rnldnkp** [officecenter/Autotask#1]
First of all, many thanks for this great PS Module!!

I have one issue though.
When I search for an account and one of the properties is empty, it does not return it.

For example:
Get-AtwsAccount -Filter {KeyAccountIcon -eq 1 -or KeyAccountIcon -eq ''}

I also tried (example would have 1,2,3 and empty as value):
Get-AtwsAccount -Filter {KeyAccountIcon -ne 2 -and KeyAccountIcon -ne 3}

If I remove all filters it returns the account just fine.

Something I'm doing wrong maybe?
Also tried $null IsEmpty etc.

**Comment by klemmestad** [comment]
We are looking into how to specify $null as a search filter using parameters. But until we figure that out you can try:
Get-AtwsAccount -Filter {KeyAccountIcon -isnull}

'-isnull' is a special QueryXML operator, so it not easy to guess that you may need it...

Hope that helps!

**Comment by rnldnkp** [comment]
That works like a charm! Thanks for the quick answer

**Comment by klemmestad** [comment]
I think we have solved the issue now. I have updated the module on PSGallery, too. With the updated module you can use:
```powershell
  Get-AtwsAccount -IsNull KeyAccountIcon # or any other parameter, of course
# and
  Get-AtwsAccount -IsNotNull KeyAccountIcon
```
