### ISSUE TITLE
Receiving this error when importing the Autotask Module. I am using an API User.

### ISSUE THREAD

**Issue by Octopistachio** [officecenter/Autotask#19]
Get-AtwsData : Exception calling "query" with "1" argument(s): "Client found response content type of 'text/html; charset=utf-8', but 
expected 'text/xml'.
The request failed with the error message:
--
<!DOCTYPE html>
<html>
    <head>
        <title>Version 1.6 of the API is only accessible to API Only users.</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>
    <body bgcolor="white">
            <span><H1>Server Error in '/ATServices' Application.<hr width=100% size=1 color=silver></H1>
            <h2> <i>Version 1.6 of the API is only accessible to API Only users.</i> </h2></span>
            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">
            <b> Description: </b>An unhandled exception occurred during the execution of the current web request. Please review the 
stack trace for more information about the error and where it originated in the code.
            <br><br>
            <b> Exception Details: </b>System.Web.Services.Protocols.SoapException: Version 1.6 of the API is only accessible to API 
Only users.<br><br>
            <b>Source Error:</b> <br><br>
            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code>
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of 
the exception can be identified using the exception stack trace below.</code>
                  </td>
               </tr>
            </table>
            <br>
            <b>Stack Trace:</b> <br><br>
            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>
[SoapException: Version 1.6 of the API is only accessible to API Only users.]
   autotask.web.services.Global.ProcessApplicationAuthenticateRequest(Boolean& bFailed, String& strDeniedReason) +1713
   AutotaskApiApplication.Global.Application_AuthenticateRequest(Object sender, EventArgs e) +42
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69
</pre></code>
                  </td>
               </tr>
            </table>
            <br>
            <hr width=100% size=1 color=silver>
            <b>Version Information:</b> Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34280
            </font>
    </body>
</html>

--."
At C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.1\Private\Connect-AtwsWebServices.ps1:155 char:15
+ ...   $Result = Get-AtwsData -Entity Resource -Filter "username -eq $User ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AtwsData], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException,Get-AtwsData
 
Import-Module : The module to process 'Autotask.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Program 
Files\WindowsPowerShell\Modules\Autotask\1.6.2.1\Autotask.psd1' was not processed because no valid module was found in any module 
directory.
At line:28 char:5
+     Import-Module Autotask -ArgumentList $Credential, $ApiKey, '*'
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Autotask:String) [Import-Module], PSInvalidOperationException
    + FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by elpeyi** [comment]
As per stated in the Autotask 1.6 documentation:

"Only resources with an API User (API-only) security level can access the API version 1.6
The API User (API-only) security level is now required to access API v1.6. It provides full system administrator access to Autotask PSA modules, features, and data via the Autotask Web Services API, with no access to the Autotask UI."

You should create an API user in Autotask Resource Admin:
https://kb.datto.com/hc/en-us/articles/360001225706-The-Created-Autotask-User-Cannot-Access-the-Webservices-API

**Comment by Octopistachio** [comment]
I changed the start of my script to the code that @cody-chapman recommended in another ticket and it seems to be running much better.

If (Get-InstalledModule "Autotask" -ErrorAction SilentlyContinue) {
Remove-Module "Autotask" -Force -Confirm:$False -ErrorAction SilentlyContinue | Out-Null
Update-Module "Autotask" -Force -Confirm:$false
}
else {
Install-Module "Autotask" -Force -Confirm:$false
}

$password = "password" | ConvertTo-SecureString -asPlainText -Force
$username = "username@domain.com"
$Credential = New-Object System.Management.Automation.PSCredential($username, $password)

$AutoTaskAPIToken = "APITOKEN" #enter your own api token key
Import-Module Autotask -ArgumentList $Credential, $AutoTaskAPIToken, '*'
