### ISSUE TITLE
Filters with parenthesis no longer work

### ISSUE THREAD

**Issue by creover** [officecenter/Autotask#2]
For your example code that you provide:

$DueFrom = Get-Date
$DueTo = $DueFrom.AddDays(3)
$Tickets = Get-AtwsTicket -Filter {DueDateTime -gt $DueFrom -and DueDateTime -lt $DueTo}
$OtherTickets = Get-AtwsTicket -Filter {Status -eq New -or (DueDateTime -gt $DueFrom -and DueDateTime -lt $DueTo)}

The following happens:
ConvertTo-QueryXML : Cannot bind argument to parameter 'QueryText' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\0.2.1.3\Public\Get-AtwsData.ps1:179 char:22
+     [xml]$QueryXml = ConvertTo-QueryXML @Query
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertTo-QueryXML], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,ConvertTo-QueryXML
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\0.2.1.3\Public\Get-AtwsData.ps1:181 char:5
+     Write-Verbose ('{0}: QueryXml looks like: {1}' -F $MyInvocation.M ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\0.2.1.3\Public\Get-AtwsData.ps1:195 char:7
+       $field = $QueryXml.CreateElement('field')
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\0.2.1.3\Public\Get-AtwsData.ps1:196 char:7
+       $expression = $QueryXml.CreateElement('expression')
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Method invocation failed because [System.String] does not contain a method named 'SetAttribute'.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\0.2.1.3\Public\Get-AtwsData.ps1:197 char:7
+       $expression.SetAttribute('op','greaterthan')
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
 
The property 'InnerText' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\0.2.1.3\Public\Get-AtwsData.ps1:198 char:7
+       $expression.InnerText = 0
+       ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
 
The property 'InnerText' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\0.2.1.3\Public\Get-AtwsData.ps1:199 char:7
+       $field.InnerText = 'id'
+       ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\0.2.1.3\Public\Get-AtwsData.ps1:200 char:7
+       [void]$field.AppendChild($expression)
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Exception calling "query" with "1" argument(s): "System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at AutotaskApiApplication.Contract.AutotaskApiService.InitializeFrameworkForRequest(String xmlRequest)
   at AutotaskApiApplication.API.V1_5.AutotaskApiService_1_5.query(String sXML)
   --- End of inner exception stack trace ---"
At C:\Program Files\WindowsPowerShell\Modules\Autotask\0.2.1.3\Public\Get-AtwsData.ps1:208 char:9
+         $lastquery = $atws.query($QueryXml.InnerXml)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SoapException
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\0.2.1.3\Public\Get-AtwsData.ps1:219 char:9
+         $UpperBound = $lastquery.EntityResults[$lastquery.EntityResul ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
The property 'InnerText' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\0.2.1.3\Public\Get-AtwsData.ps1:220 char:9
+         $expression.InnerText = $UpperBound
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\0.2.1.3\Public\Get-AtwsData.ps1:224 char:11
+           [void]$QueryXml.queryxml.query.AppendChild($field)
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by klemmestad** [comment]
Thank you for reporting this. 

I have fixed this and uploaded an updated module. 
Please note that I have found an error in our documentation on this point: Custom filters does not expand picklist values. The correct example should have been ('New' has been replaced by its numerical value): 

```PowerShell
$OtherTickets = Get-AtwsTicket -Filter {Status -eq 1 -or (DueDateTime -gt $DueFrom -and DueDateTime -lt $DueTo)}
```

This query should work with the newest module.
