### ISSUE TITLE
new-atwscontract: System.dateTime: Can not convert data to date in field

### ISSUE THREAD

**Issue by dahifi** [officecenter/Autotask#20]
I'm trying to figure out the proper way to specify the EndDate and StartDate. 

Tried passing a string; casting like `
$enddate = ([datetime]"05-31-2022")` and have even tried passing `$enddate.datetime` and still getting this error: 

`New-AtwsData : Can not convert data to date in field: EndDate. ; on record number [1].
At New-AtwsContract.ps1:467 char:15
+     $Result = New-AtwsData -Entity $ProcessObject
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AtwsData`

I've checked the type of the object I'm passing, and it's DateTime, which is what the function says it requires.

**Comment by klemmestad** [comment]
That looks like a bug. I will have to dedicate a bit of time to fixing up and simplifying this module again. Too many bugs are introduced with new versions. 

Workaround: 
```powershell
$Contract = New-Object -Typename Autotask.Contract
$Contract.enddata = $enddate
# and set any other required and optional field you need

New-AtwsContract -InputObject $Contract
```
 Creating the object first and setting field values that way should get you passed the bug while I get it fixed.

**Comment by dahifi** [comment]
Thanks! 

Is there a better way to get picklist values than this mess? 

`(Get-AtwsFieldInfo -Entity contract | where-object -filterscript {$_.name -eq 'ContractPeriodType'}).picklistvalues`
