### ISSUE TITLE
Help w/ picklists lookups in functions and scripts. 

### ISSUE THREAD

**Issue by dahifi** [officecenter/Autotask#23]
So the powershell ISE command view does a great job of pulling the picklist values in, but I'm trying to figure out a friendly way to refer to these values when building out my scripts. 

For example, I want to write a function to set ticket statuses to closed: 
```
function close-atwsticket($ticketNumber) {
    $ticket = Get-AtwsTicket -TicketNumber $ticketNumber
    $ticket.status = 'Complete'
    $ticket | set-atwsTicket
}
```
This will fail: `WARNING: Element with index 0 of type Ticket with Id 36502 was skipped because Picklist value [complete] does not exist for Status. `

So I wrote another function: 
```
function get-picklistvalues {
    param (
        [String]
        $Entity, 

        [String]
        $Picklist
    )

    $results = (Get-AtwsFieldInfo -Entity $Entity | where-object -filterscript {$_.name -eq $Picklist}).picklistvalues
    return $results
}
```
Where I can run `get-picklistvalues "Ticket" "Status"` and manually search or pipe to where-object to find the one I'm looking for. 

I'm assuming that there's an easier way to do this?

**Comment by dahifi** [comment]
This is what I came up with. I assume my limited knowledge of advanced PS techniques is making this harder than it needs to be... 

```
function close-atwsticket($ticketNumber) {
    $ticket = Get-AtwsTicket -TicketNumber $ticketNumber
    $complete = (get-picklistvalues "Ticket" "Status" |where-object {$_.Label -eq "Complete"}).value
    $ticket.status = $complete
    $ticket | set-atwsTicket
}
```

**Comment by klemmestad** [comment]
I am not sure if this was a misjudgement on my part when creating the module, but I only do picklist substitution when you use parameters. On the upside this means that the set- function already do the lookup that you have coded in your get-picklistvalues function. An example:
```powershell
function close-atwsticket($ticketNumber) {
    $ticket = Get-AtwsTicket -TicketNumber $ticketNumber
    $ticket | set-atwsTicket -Status Complete
}
```
This does the exact thing you are trying to do. I have considered trying to support your first version, i.e. swapping picklist index values for labels when working with objects, but I'm afraid it would break backwards compatibility with scripts already written at this point.

**Comment by klemmestad** [comment]
I have revisited the problem and think I have a solution. I simply check if any picklist field contains a label and replaces it with its numerical value before passing it to the API. I have also included an experimental feature to convert all picklist fields to their labels by default. To use this you must connect using:
```powershell
Connect-AtwsAPI -Credential $Credential -ApiTrackingIdentifier $ApiKey -UsePicklistLabels
```
Your original close-atwsticket function now works in my tests.

**Comment by dahifi** [comment]
Dude you are NINJA. I'm going to have to look over this and figure out how you do it. Auto generating the functions based on the AT API? That seem like magic to me. 

I may be able to contribute some tests to the module if I ever have time, This module is going to TRANSFORM how we operate, and hopefully I'll be able to contribute some functions that will help stand up our new sites -- we're an MSP franchise that that has about 200 individual operators, and templating our operations using this module is going to be my focus for the next 6 months.

**Comment by dahifi** [comment]
Looks good, although selecting a picklist in the ISE by_parameters fails if the field contains a space. Wrapping it in quotes does the job though.

**Comment by klemmestad** [comment]
Feel free to post that as an issue. I _think_ I know how to solve that...

**Comment by klemmestad** [comment]
I take that back. My test failed miserably. But nor do I have your problem in ISE (Windows 10, PowerShell 5.1). ISE adds single quotes automatically when a picklist value contains space. Or maybe I don't understand where your problem is. Could you create an issue and include an example?

**Comment by dahifi** [comment]
Win10, 5.1. ISE doesn't put quotes for anything I put in command window. Ever. who knows, maybe you're using a plugin? Doesn't matter

 Just read on MS web that the ISE is in 'maintenance mode' and isn't likely to be updated, so I'm going to switch over to VSCode. Thanks again for making a banging-ass module. I wish the python module was as good as this one....
