### ISSUE TITLE
Set-AtwsTicket.ps1 - int32[] to int64 conversion error

### ISSUE THREAD

**Issue by MitchellVanHorn** [officecenter/Autotask#25]
When running "Set-AtwsTicket -id <SomeID> @param", the command will successfully run, however it will throw the below error: 
[int32[]] cannot be converted to [int64]
...\Cache\2946\Dynamic\Set-AtwsTicket.ps1:715 char: 21

```
Exception setting "Id": "Cannot convert the "System.Int32[]" value of type "System.Int32[]" to type "System.Int64"."
At C:\Users\UserName\Documents\WindowsPowershell\Cache\2946\Dynamic\Set-AtwsTicket.ps1:715 char:21
+           $Object.$($Parameter.Key) = $Value
+                     ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
```

**Comment by klemmestad** [comment]
I thought I had fixed this, but it turns out I only fixed it for Get- functions ☹️
I have a fix in the works.

**Comment by MitchellVanHorn** [comment]
Awesome. By the way, thanks for the awesome module!

**Comment by klemmestad** [comment]
New module version with fix should be uploaded within the hour.
