### ISSUE TITLE
Receiving Confirm prompts with $global:ConfirmPreference="None"

### ISSUE THREAD

**Issue by Shammack** [officecenter/Autotask#27]
When issuing both New-AtwsTicket and New-AtwsTimeEntry, I still receive a confirmation prompt. The Always-on VERBOSE message from New-AtwsData properly shows that the ConfirmPreference is set to "None".

**Comment by Shammack** [comment]
To further expand on this, we're just trying to get better automation out of our script when it creates new tickets or adds time entries. Presently, any script we use that creates a new ticket or time entry requires a manual confirm regardless of any attempts to bypass the confirm prompt (e.g. $ConfirmPreference="None", -confirm:$false, -force, etc.)

If you have a means for us to issue the New-Atws[Ticket|TimeEntry] commands without receiving the prompt, it would be greatly appreciated. Apologies if I'm missing a simple solution here.

**Comment by klemmestad** [comment]
Could you try with $ConfirmPreference = "High"? A colleague of mine is also seeing erratic confirm behavior with $ConfirmPreference = "None". For some reason I cannot reproduce the confirmation prompt on my system. 

Are you using VSCode or ISE to run your code?

**Comment by klemmestad** [comment]
This should be solved from version 1.6.2.12.

**Comment by Shammack** [comment]
Hi Hugo, I'm sorry for missing your prior note on this. I can confirm that I am no longer seeing the confirmation prompts when using my code following some other changes. None of those changes should have affected the confirmation prompts, so whatever you did must have fixed it.

Thank you for all you do! Your module is greatly appreciated here.
