### ISSUE TITLE
Set-AtWsTicketCost - Update status

### ISSUE THREAD

**Issue by rtenklooster** [officecenter/Autotask#28]
Hi,
Thanks again for the modifications you made to make this work in Azure Automations.
So far it's working great. 

Currently i'm working on a Office 365 PowerApp witch is used to let the customers sign for received prodcucts. Every hour the runbooks runs, gets all ticketCosts and saves them to a sharepoint list. 

The PowerApp allows me to select the items for the selected customer, and make them sign.
![djuUHa5Pwp](https://user-images.githubusercontent.com/6507714/58805184-e0786d00-8613-11e9-8835-894da00c0384.gif)

When the customer has signed, I want to update the Quantity and the status. 
Updating the quantity works, the status however isn't saved.
My question is, can this be done by the API, or is it just not the way it workes.

Sample code, only saving the quantity:

```
$test = Get-AtwsTicketCost -id 29689473
$test

$test.UnitQuantity = 2 
$test.Status = 5

$test | Set-AtwsTicketCost

```

**Comment by klemmestad** [comment]
Great work! It is nice to see the module in use! :) That is a very nice idea! Would you be able to share some of the steps you have gone through to get this far in a blog post somewhere? Or you could publish it here alongside the module documentation?

Unfortunately the Status field is Read-Only according to the [API documentation](https://ww4.autotask.net/help/Content/LinkedDOCUMENTS/WSAPI/T_WebServicesAPIv1_5.pdf) (page 346) so you cannot update the cost status through the API. At first look it seems to be because the cost status is integrated with procurement.

Are all the costs connected to the same ticket? Maybe you'd be able to solve it with Ticket status? Or a ticket UDF?

**Comment by rtenklooster** [comment]
> Are all the costs connected to the same ticket? Maybe you'd be able to solve it with Ticket status? Or a ticket UDF?
Hmm, I guess i'm out of luck. If I assume there is one item per ticket it still wouldn't give me an option to update the status. The tickets (opportunities) for items waiting to be delivered are already closed.
I've tried looking at workflow rules in AT to see if it's possible to use an UDF as a trigger, but in workflow rules the option to set an item shipped is absent as well. 

I think I go for the workaround; when an item is marked as delivered / shipped in the PowerApp, I send a daily mail will all delivered items to the sales manager. They have to manually update the item in the delivery / shipping overview. 

Thanks again for your support. I'm thinking about writing a blog to publish some of the code / solutions.

**Comment by rtenklooster** [comment]
Hmm starting to dislike AutoTask more and more. I don't get why their API is so limited.
We offer some some services, licensed on a per-user base.
Using flow we get the active users from a customer's tennant, write the amount of active users back to SharePoint. 

My idea was to run a runbook every month, updating contracts when the amount of active users has been changed. So far so good. Everything is working except: 
![image](https://user-images.githubusercontent.com/6507714/60419729-4aba0880-9be6-11e9-87e3-770394c8745d.png)

Stupid system.

**Comment by klemmestad** [comment]
You can do this, but the syntax is not what you expect and the object you need is not ContractServiceUnit. The datamodel is probably quite complex beneath all this. There are no way, neither through the API, nor the GUI to just modify the contract service units directly. But you can add or subtract users (service units) using `New-AtwsContractServiceAdjustment`

Hope that helps!

**Comment by rtenklooster** [comment]
You are amazing! Exactly what I was looking for! Now I'm able to automatically adjust the contract items :) Thanks a lot!!
