### ISSUE TITLE
Value does not exist for the required field when using New-AtwsData -InputObject

### ISSUE THREAD

**Issue by cygnus6** [officecenter/Autotask#3]
Hi Guys,

First of all thank you for this project. We are in the process of migrating to Autotask and this tool is already very useful.

I did get an error while using the following command:
```
New-AtwsContact -InputObject $Contact`
It responds:
`New-AtwsData : Value does not exist for the required field AccountID. ; on record number [1].
At line:52822 char:15
+     $Result = New-AtwsData -Entity $ProcessObject -Connection $Prefix
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AtwsData
```

The Account object does not have this problem, while the AccountAlert object does.
I can fix it by using the other parameterset, but I'd rather use the InputObject.

I think it has something to do with the AccountID field being marked Readonly, but unfortunately I can't find the correct fix. Would you be able to have a look?

Thanks!

**Comment by klemmestad** [comment]
I will check that, but since I don't have access to your tenant, could you please verify the Account Id value of your contact by trying the command below and report back? It should return the account you are trying to connect your Contact object to.

```powershell
Get-AtwsAccount -Id $Contact.AccountId
```

**Comment by cygnus6** [comment]
Sorry for the delay,
I added 2 scripts to show the problem, including your Get-AtwsAccount code. If you fill in your own data 
where the ##### are you should be able to replicate the problem.

Working:
` $User = "########"
$PWord = ConvertTo-SecureString -String "#######" -AsPlainText -Force
$Credentials = New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList $User, $PWord
Connect-AutotaskWebAPI -Credential $Credentials

$Account = Get-AtwsAccount -AccountName "#######"

$Contact = New-Object Autotask.Contact
$Contact.AccountID = $Account.id
$Contact.FirstName = "First"
$Contact.LastName = "Last"
$Contact.Active = $true

Get-AtwsAccount -Id $Contact.AccountID

$NewContact = New-AtwsContact -AccountID $Contact.AccountID -FirstName $Contact.FirstName -LastName $Contact.LastName -Active $Contact.Active
`

Not Working:
` $User = "######"
$PWord = ConvertTo-SecureString -String "#########" -AsPlainText -Force
$Credentials = New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList $User, $PWord
Connect-AutotaskWebAPI -Credential $Credentials

$Account = Get-AtwsAccount -AccountName "#########"

$Contact = New-Object Autotask.Contact
$Contact.AccountID = $Account.id
$Contact.FirstName = "First"
$Contact.LastName = "Last"
$Contact.Active = $true

Get-AtwsAccount -Id $Contact.AccountID

$NewContact = New-AtwsContact -InputObject $Contact
`

**Comment by klemmestad** [comment]
Thank you! This is very useful error reporting. I am travelling right now, but I will look into it as soon as possible.

**Comment by klemmestad** [comment]
Thank you again! This turned out to be a logical error that affects most _New-_ functions. I will fix it and upload a module update.

**Comment by cygnus6** [comment]
Thank you for the fix! I can confirm this works correctly for my code.
I did find another issue updating from 0.2.1.5 to 0.2.1.7. I created a pull request to resolve it.
