### ISSUE TITLE
No DefaultServiceDeskRoleID parameter on the Get-AtwsResource function

### ISSUE THREAD

**Issue by JsonWud** [officecenter/Autotask#31]
I thought I was seeing a bug in the old 1.5 version, so I switched to the latest 1.6.2.11 module, but found the same behavior.

I want to grab all active resources with a specific DefaultServiceDeskRoleID. Based on my experience with your modules in the past, I expected to simply call this:

`Get-AtwsResource -Active $true -DefaultServiceDeskRoleID xxxxxxxx`

But I have found that the DefaultServiceDeskRoleID parameter does not exist. The only mention is in the GetReferenceEntityById parameter's ValidateSet value. Why not have the DefaultServiceDeskRoleID as a parameter itself? Am I missing something?

Thanks,
Jason

**Comment by klemmestad** [comment]
The DefaultServiceDeskRoleID field unfortunately isn't queryable. I am afraid you will have to `Get-AtwsResource -All | Where-Object {}` in your code. I do not know why the field cannot be queried, only that it is marked as not queryable when I call the .GetFieldInfo('resource') method:

```powershell
Name                     : DefaultServiceDeskRoleID
Label                    : Default Service Desk Role
Type                     : long
Length                   : 0
Description              : 
IsRequired               : False
IsReadOnly               : False
IsQueryable              : False
IsReference              : True
ReferenceEntityType      : Role
IsPickList               : False
PicklistValues           : 
PicklistParentValueField : 
DefaultValue             : 
```

**Comment by JsonWud** [comment]
I'm sorry, I completely skipped over this section in the api doc:

Fields that cannot be queried:
The following fields from this entity will return an error when queried.
DefaultServiceDeskRoleID
Password

Very puzzled as to why Autotask would do that. Oh well. Thanks again!
