### ISSUE TITLE
Get / Set AccountManager field

### ISSUE THREAD

**Issue by teejayen** [officecenter/Autotask#4]
Loving the module so far, and has made light work of a couple of bulk changes for us.

Currently, there's no easy way to bulk modify the Account Manager assigned to an account in Autotask -  so leveraging the API through your PoSH module would work really well! 

It would be invaluable to be able to Get / Set the AccountManager field using AtwsAccount.

**Comment by klemmestad** [comment]
Hi, glad you find our module useful! :)

The Account Manager field is exposed in the API as owner resource. I guess that is why you haven't found it yet. The field name is _OwnerResourceId_:

```powershell
# Get Account Manager for $Account
$AccountManager = Get-AtwsResource -id $Account.OwnerResourceId
Write-Output ('The Account Manager for Account {0} is {1} {2}' -F $Account.AccountName, $AccountManager.FirstName, $AccountManager.LastName

# Bulk change Account Manager
$PreviousManager = Get-AtwsResource -Username '<previousmanager_username>'
$NewManager = Get-AtwsResource -Username '<newmanager_username>'

Get-AtwsAccount -OwnerResourceId $PreviousManager.id | Set-AtwsAccount -OwnerResourceId $NewManager.id
```

**Comment by teejayen** [comment]
Thanks very much, that's perfect!
