### ISSUE TITLE
New-AtwsTicketNote -Publish not recognised by cmdlet

### ISSUE THREAD

**Issue by MondQ** [officecenter/Autotask#45]
Hi,
When I run
`New-AtwsTicketNote -Description "Test" -TicketID $Ticket.id -Title "Bread" -NoteType "Task Summary" -Publish "1"`

I get the following error
`New-AtwsData : Missing Required Field: Publish. ; on record number [1].
At C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.13\Dynamic\New-AtwsTicketNote.ps1:242 char:17
       $Result = New-AtwsData -Entity $ProcessObject
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AtwsData`

I am not sure what value to assign to -Publish, as the cmdlet expects a string and the API documentation says it's and integer, but I get the error either way

Module version 1.6.2.13

Let me know if you need any more information.

**Comment by klemmestad** [comment]
Hi,
When I try the same command Intellisense gives me two options: 'All Autotask Users' or 'Internal Project Team'. Which editor are you using? ISE suggests automatically, while VSCode waits until I type something.

**Comment by MondQ** [comment]
Hi klemmestad,
Thanks for your reply. Turns our that if I use the two options you mentioned, the cmdlet works. Intellisense still won't suggest values in VS Code, or ISE for me though, which is why I had no indication as to what to put as the value and unfortunately there were no explicit examples in the get-help information.

The values not appearing is probably a local issue.

Cheers.
