### ISSUE TITLE
Username / Password issues

### ISSUE THREAD

**Issue by CCS-StevenPretlove** [officecenter/Autotask#46]
getting a wierd error that is returning as a username / password error (it deff isn't as i've had Autotask check there internal tool and they are working)

can i export the XML sent / returned to check for any "oddities" Verbose is showing the attempt to create the webservice but this is then failing.

Autotask say its more likely because of "malformed XML" but i can't see it to move the issue along

VERBOSE: Connect-AtwsWebServices: Getting ZoneInfo for user \api.support@XXX.CO.UK by calling default URI https://webservices.Autotask.net/atservices/1.6/atws.wsdl
VERBOSE: Connect-AtwsWebServices: Customer tenant ID: XXX, Web URL: https://ww16.autotask.net/, SOAP endpoint: https://webservices16.autotask.net/ATServices/1.6/atws.asmx
VERBOSE: Connect-AtwsWebServices: Creating New-WebServiceProxy against URI: https://webservices16.autotask.net/ATServices/1.6/atws.wsdl
import-module : Could not connect to Autotask WebAPI. Verify your credentials. If you are sure you have the rights - maybe you typed your password wrong?

**Comment by CCS-StevenPretlove** [comment]
having spent some time pulling it apart this seams to be the issue

Exception setting "AutotaskIntegrationsValue": "Cannot convert the "Autotask.AutotaskIntegrations" value of type "Autotask.AutotaskIntegrations" to type "Autotask.AutotaskIntegrations"."

**Comment by CCS-StevenPretlove** [comment]
it seems that if i try and authenticate against ww16 i get this error thrown but if i go against ww4 it does not, i have tried 2 sets of credentials against ww16 and get the same result however ww4 doesn't through this error

**Comment by klemmestad** [comment]
The only error I can think of that would cause this is if the webservices16 endpoint did not support version 1.6 completely, yet. But when I test today everything works. Do you still get an error when you try? 
```powershell
PS > $Proxy = New-WebServiceProxy -URI 'https://webservices16.autotask.net/ATServices/1.6/atws.wsdl' -Namespace 'test1' -Class 'AutotaskAPI' -ErrorAction Stop
new-object test1.AutotaskIntegrations

PartnerID                        : 
IntegrationCode                  : 
ImpersonateAsResourceID          : 0
ImpersonateAsResourceIDSpecified : False
AnyAttr                          : 
EncodedMustUnderstand            : 0
EncodedMustUnderstand12          : 0
MustUnderstand                   : False
Actor                            : 
Role                             : 
DidUnderstand                    : False
EncodedRelay                     : 0
Relay                            : False

PS > $Proxy = New-WebServiceProxy -URI 'https://webservices4.autotask.net/ATServices/1.6/atws.wsdl'  -Namespace 'test2' -Class 'AutotaskAPI' -ErrorAction Stop
new-object test2.AutotaskIntegrations

PartnerID                        : 
IntegrationCode                  : 
ImpersonateAsResourceID          : 0
ImpersonateAsResourceIDSpecified : False
AnyAttr                          : 
EncodedMustUnderstand            : 0
EncodedMustUnderstand12          : 0
MustUnderstand                   : False
Actor                            : 
Role                             : 
DidUnderstand                    : False
EncodedRelay                     : 0
Relay                            : False
```

**Comment by CCS-StevenPretlove** [comment]
Thanks Hugo,

I think we have tracked down the issue (well how do get around it), it appears that for some reason the module / the windows PS ISE, can get in a flap, uninstalling / re-installing the module resolved the issue (for a while) but equally so does restarted the ISE its very bizarre

Regards



Steven Pretlove
Managing Director
Steven.Pretlove@ccsnet.co.uk
01908 410041
07595 020702
www.ccsnet.co.uk
Gemini House, Sunrise Parkway, Linford Wood, Milton Keynes, MK14 6LS
Disclaimer: County Consultancy Services Ltd. may monitor email traffic data and also the content of email for the purposes of security and staff training.
 This message contains confidential information and is intended only for the reciepient. If you are not the recipient you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. CCS IT Solutions therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.
 Terms and Conditions: All services and quotes that may or may not be contained within this e-mail are bound by our standard terms and conditions the latest version of which can be found on our website.
 County Consultancy Services Ltd. (CCS) is a limited company registered in England and Wales 5185670.
 Registered office: Gemini House, Sunrise Parkway, Linford Wood, Milton Keynes, MK14 6LS

**Comment by klemmestad** [comment]
The module builds on the New-WebServiceProxy cmdlet. It somehow creates a .NET object with the SOAP API methods dynamically compiled in. This object exists more or less outside the powershell session the module runs in. Experience has shown that after you have created this object (i.e. the first connection), new calls to New-WebServiceProxy will not return a new object. One of the symptoms is that it is nigh on impossible to change credentials after the first connection. Which can be a pain if you got the password wrong, for instance. A restart of ISE usually solves it, but I (and others) have had to reboot, too.

It has been months since the last time it happened to me, so this may also be affected by patches to powershell on my development machine for all I know...

**Comment by CCS-StevenPretlove** [comment]
Hi Hugo,

I’ve checked with support who say the UDF is available, I’ve rebooted and tried on another PC which gives the same result (although not from a fresh install which is next on the list)

I’m pretty much out of ideas ATM

Regards



Steven Pretlove
Managing Director
Steven.Pretlove@ccsnet.co.uk
01908 410041
07595 020702
www.ccsnet.co.uk
Gemini House, Sunrise Parkway, Linford Wood, Milton Keynes, MK14 6LS
Disclaimer: County Consultancy Services Ltd. may monitor email traffic data and also the content of email for the purposes of security and staff training.
 This message contains confidential information and is intended only for the reciepient. If you are not the recipient you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. CCS IT Solutions therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.
 Terms and Conditions: All services and quotes that may or may not be contained within this e-mail are bound by our standard terms and conditions the latest version of which can be found on our website.
 County Consultancy Services Ltd. (CCS) is a limited company registered in England and Wales 5185670.
 Registered office: Gemini House, Sunrise Parkway, Linford Wood, Milton Keynes, MK14 6LS

**Comment by CCS-StevenPretlove** [comment]
Hi Hugo,

I’m very confused now, this works fine under 0.2.2.1 (which we had installed on a old laptop)

So

Import-Module Autotask
#$Credential = Get-Credential

$username = 'steven.pretlove@****.co.uk'
$password = convertto-securestring -String '****’ -AsPlainText -Force

$Credential = new-object -typename System.Management.Automation.PSCredential `
         -argumentlist $username, $password
Connect-AutotaskWebAPI -Credential $Credential

$test = Get-AtwsInstalledProduct -id 29683721

$test.UserDefinedFields


Works  fine and I can see the UDF field and as I change it the new value comes up

# Username and password for Autotask
$ATurl = "https://webservices.autotask.net/ATServices/1.6/atws.wsdl" # To use Version 1.6 change to "https://webservices.autotask.net/ATServices/1.6/atws.wsdl"

$ATusername = "api.steve@******.co.uk"
$ATpassword = ConvertTo-SecureString "*******" -AsPlainText -Force

$ATcredentials = New-Object System.Management.Automation.PSCredential($ATusername,$ATpassword)

$APIKey = '*********'

Import-Module Autotask -ArgumentList $ATcredentials, $APIKey -verbose -Prefix CCS -force

$test = Get-CCSAtwsInstalledProduct -id 29683721

Returns the values and UDFs (as it was prior to adding the new UDF) if I change values the new values show up and change as you would expect. But I cannot get the new UDF to show up for love nor money.

Regards

From: Steven Pretlove | CCS IT Solutions
Sent: 11 August 2019 11:50
To: officecenter/Autotask <reply@reply.github.com>; officecenter/Autotask <Autotask@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [officecenter/Autotask] Username / Password issues (#46)

Hi Hugo,

I’ve checked with support who say the UDF is available, I’ve rebooted and tried on another PC which gives the same result (although not from a fresh install which is next on the list)

I’m pretty much out of ideas ATM

Regards



Steven Pretlove
Managing Director
Steven.Pretlove@ccsnet.co.uk
01908 410041
07595 020702
www.ccsnet.co.uk
Gemini House, Sunrise Parkway, Linford Wood, Milton Keynes, MK14 6LS
Disclaimer: County Consultancy Services Ltd. may monitor email traffic data and also the content of email for the purposes of security and staff training.
 This message contains confidential information and is intended only for the reciepient. If you are not the recipient you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. CCS IT Solutions therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.
 Terms and Conditions: All services and quotes that may or may not be contained within this e-mail are bound by our standard terms and conditions the latest version of which can be found on our website.
 County Consultancy Services Ltd. (CCS) is a limited company registered in England and Wales 5185670.
 Registered office: Gemini House, Sunrise Parkway, Linford Wood, Milton Keynes, MK14 6LS

**Comment by CCS-StevenPretlove** [comment]
reboots / ISE restarts resolve the issue thank you
