### ISSUE TITLE
Doc suggestion for null values

### ISSUE THREAD

**Issue by AlexHeylin** [officecenter/Autotask#6]
Thanks for this module - very useful!

I hit a problem trying to query for null values (such as ticket.AssignedResourceID to mean unassigned).  I found the docs sparse regarding null values, and typing prevents query by parameters from working.

This is more complex, but works - perhaps you'd add as an example to the docs. It gets unassigned tickets in our "1st line support" queue that have not been updated in two hours (set on line 2)

```
$AtDbUtcOffset = -4.0
$LastUpdateDateTimeEST = (get-date).AddHours(+$AtDbUTCOffset).AddHours(-2)
$Tickets1stLine = Get-AtwsTicket  -Filter { AssignedResourceID -isnull -and  QueueID -eq 29682833 -and (Status -eq 1 -or Status -eq 8 ) -and LastActivityDate -lt $LastUpdateDateTimeEST } 
$Tickets1stLine | ft AssignedResourceID , QueueID , TicketNumber, Title, LastActivityDate
```

**Comment by klemmestad** [comment]
Thank you! You are right, null values are not properly documented. I will try to get it updated as soon as time permits. Another weak point in our documentation is release notes. We have added support for null values in queries along the way, but it is not easy to find. Could I bother you to try this query to see if it gives you the same result as your query:

`$AtDbUtcOffset = -4.0
$LastUpdateDateTimeEST = (get-date).AddHours(+$AtDbUTCOffset).AddHours(-2)
$Tickets1stLine = Get-AtwsTicket  -IsNull AssignedResourceID -QueueID <queuename> -Status <status 1>,<status 8> -LastActivityDate $LastUpdateDateTimeEST -LessThan LastActivityDate 
$Tickets1stLine | ft AssignedResourceID , QueueID , TicketNumber, Title, LastActivityDate1
`

**Comment by AlexHeylin** [comment]
Thanks for this. Sure, I'll run that tomorrow - just checking, do you want
me to use the text lookup values, or the numeric IDs for queue name and
statuses?

Thanks

Alex

**Comment by klemmestad** [comment]
Text values. Parameter validation will reject the numeric ids.

Med vennlig hilsen
Hugo Klemmestad


30. mai 2018 kl. 02:26 skrev AlexHeylin <notifications@github.com<mailto:notifications@github.com>>:

Thanks for this. Sure, I'll run that tomorrow - just checking, do you want
me to use the text lookup values, or the numeric IDs for queue name and
statuses?

Thanks

Alex

**Comment by AlexHeylin** [comment]
That works very well and is much easier to write and read. :-D
Wishlist for the docs - examples of the less common operators (for example the -IsNull FieldName seems backwards to me), & full clear list of operators - I found myself trying to guess  them and their syntax based on Autotask API docs.
Thanks very much!

**Comment by klemmestad** [comment]
I have updated the documentation by adding a separate page where I try to explain how null values are handled. The documentation could still be improved, but I am closing this issue now.
